//
// Created by Ivan Garzon on 2020-02-24.
//

#ifndef COMP345_NEWHAVENPROJECT_CORNERSTYPES_H
#define COMP345_NEWHAVENPROJECT_CORNERSTYPES_H

#include <map>

enum Corners {
	TOP_LEFT,
	TOP_RIGHT,
	BOTTOM_LEFT,
	BOTTOM_RIGHT
};

#endif //COMP345_NEWHAVENPROJECT_CORNERSTYPES_H
