#ifndef COMP345_NEWHAVENPROJECT_GAMESTARTDRIVER_H
#define	COMP345_NEWHAVENPROJECT_GAMESTARTDRIVER_H

class GameStartDriver {
public:
	static void gameStart();
};
#endif // !COMP345_NEWHAVENPROJECT_GAMESTARTDRIVER_H
